---
# file: dev_create.yml
- hosts: dev
  connection: local
  gather_facts: yes
  vars_files:
    - ansiblevirtsvc.yml
    
  roles:
    - ovirt_auth_pre
    - ovirt_snapshots_create
    - ovirt_snapshots_report_by_description
    - ovirt_auth_post
    - mail_report_send
