---
# file: roles/ovirt_snapshots_create/tasks/main.yml
- name: Get snapshots info
  ovirt.ovirt.ovirt_snapshot_info:
    auth: "{{ ovirt_auth }}"
    vm: "{{ item }}"
    #description: beforepatch_*_by_ansible
  register: result
  loop: "{{ virtual_machine }}"

- name: Output snapshot info
  ansible.builtin.debug:
    msg:
      - "{{ result | json_query(query) }}"
  when: debug 
  vars:
    query: "results[*].[{vm: item}, ovirt_snapshots[*] | [?snapshot_type == 'regular'].{id:id, date: date, description: description}]"

- name: Create snapshot (if no exisiting snapshot)
  ovirt.ovirt.ovirt_snapshot:
    auth: "{{ ovirt_auth }}"
    vm_name: "{{ item }}"
    state: present
    use_memory: no
    description : "beforepatch_{{ ansible_facts['date_time']['date'] }}_by_Ansible"
    wait: yes
  loop: "{{ virtual_machine }}"
  when: (result | json_query(query)) is none
  #when: result.changed != false
  vars:
    query: "results[?item == '{{ item }}'].ovirt_snapshots[] | [?snapshot_type == 'regular'].id | [0]"

